enum_mappings:
  - filename: medical_history.json
    key: hypertension_measurement_type
  - filename: medical_history.json
    key: diabetes_type
  - filename: medical_history.json
    key: hypertension
  - filename: sample.json
    key: sample_provider
  - filename: lipidomics_file.json
    key: data_category
  - filename: lipidomics_file.json
    key: data_format
  - filename: lipidomics_file.json
    key: data_type
  
time_mappings:
  - filename: core_metadata_collection.json
    key: date