$schema: http://json-schema.org/draft-04/schema#
additionalProperties: false
category: administrative
constraints: null
description: The study the data is coming from
id: project
links:
- backref: projects
  label: member_of
  multiplicity: many_to_one
  name: programs
  required: true
  target_type: program
namespace: http://commons.heartdata.baker.edu.au/
program: '*'
project: '*'
properties:
  authz:
    description: The authz string (example, ["/programs/Program.name/projects/Project.code"]
      ).
    items:
      type: string
    type: array
  availability_mechanism:
    description: Mechanism by which the project will be made avilable.
    type: string
  availability_type:
    description: Is the project open or restricted?
    enum:
    - Open
    - Restricted
  code:
    description: Unique identifier for the project.
    type: string
  consent_codes:
    description: "Data Use Restrictions that are used to indicate  permissions/restrictions\
      \ for datasets and/or materials, and relates to the purposes for which datasets\
      \ and/or material might be removed, stored or used. \\n\n        Based on the\
      \ Data Use Ontology : see http://www.obofoundry.org/ontology/duo.html"
    type: array
  data_access_url:
    description: A URL link that takes you to a page that explains how to gain access
      to the project
    type: string
  date_collected:
    description: The date or date range in which the project data was collected.
    type: string
  dbgap_accession_number:
    description: The dbgap accession number provided for the project. (CMG)
    type: string
  full_name:
    description: The full name for the project.
    type: string
  id:
    description: UUID for the project.
    pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
    systemAlias: node_id
    term:
      description: 'A 128-bit identifier. Depending on the mechanism used to generate
        it, it is either guaranteed to be different from all other UUIDs/GUIDs generated
        until 3400 AD or extremely likely to be different. Its relatively small size
        lends itself well to sorting, ordering, and hashing of all sorts, storing
        in databases, simple allocation, and ease of programming in general.

        '
      termDef:
        cde_id: C54100
        cde_version: null
        source: NCIt
        term: Universally Unique Identifier
        term_url: https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.02d&ns=NCI_Thesaurus&code=C54100
    type: string
  intended_release_date:
    description: Tracks a Project's intended release date.
    format: date-time
    type: string
  name:
    description: Display name/brief description for the project.
    type: string
  programs:
    anyOf:
    - items:
        additionalProperties: true
        maxItems: 1
        minItems: 1
        properties:
          id:
            pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
            term:
              description: 'A 128-bit identifier. Depending on the mechanism used
                to generate it, it is either guaranteed to be different from all other
                UUIDs/GUIDs generated until 3400 AD or extremely likely to be different.
                Its relatively small size lends itself well to sorting, ordering,
                and hashing of all sorts, storing in databases, simple allocation,
                and ease of programming in general.

                '
              termDef:
                cde_id: C54100
                cde_version: null
                source: NCIt
                term: Universally Unique Identifier
                term_url: https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.02d&ns=NCI_Thesaurus&code=C54100
            type: string
          submitter_id:
            type: string
        type: object
      type: array
    - additionalProperties: true
      properties:
        id:
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
          term:
            description: 'A 128-bit identifier. Depending on the mechanism used to
              generate it, it is either guaranteed to be different from all other
              UUIDs/GUIDs generated until 3400 AD or extremely likely to be different.
              Its relatively small size lends itself well to sorting, ordering, and
              hashing of all sorts, storing in databases, simple allocation, and ease
              of programming in general.

              '
            termDef:
              cde_id: C54100
              cde_version: null
              source: NCIt
              term: Universally Unique Identifier
              term_url: https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.02d&ns=NCI_Thesaurus&code=C54100
          type: string
        submitter_id:
          type: string
      type: object
    description: 'Indicates that the Study is logically part of the indicated Study.

      '
  project_description:
    description: The description for the project.
    type: string
  project_registration:
    description: External source from which the identifier included in study_id originates
    type: string
  releasable:
    default: false
    description: 'A project can only be released by the user when `releasable` is
      true.

      '
    type: boolean
  released:
    default: false
    description: 'To release a project is to tell the GDC to include all submitted

      entities in the next GDC index.

      '
    type: boolean
  short_name:
    description: The shorthand name for the project.
    type: string
  state:
    default: open
    description: 'The possible states a project can be in.  All but `open` are

      equivalent to some type of locked state.

      '
    enum:
    - open
    - review
    - submitted
    - processing
    - closed
    - legacy
  support_id:
    description: The ID of the source providing support/grant resources.
    type: string
  support_source:
    description: The name of source providing support/grant resources.
    type: string
  type:
    type: string
required:
- code
- name
- programs
- dbgap_accession_number
submittable: true
systemProperties:
- id
- state
- released
- releasable
- intended_release_date
title: Project
type: object
uniqueKeys:
- - id
- - code
validators: null
