name: Build and Test

on:
  push:
    branches: [main, main-version-2]
  pull_request:
    branches: [main, main-version-2]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry to use in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry to use in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest -vv tests/